import { Metadata } from "next";
import { Award, awards } from "../app-data";

export default async function Page({ params }: { params: Promise<Award> }) {
  const slug = (await params).title;
  return <div>My Post: {slug}</div>;
}

export async function generateStaticParams() {
  return awards;
}

import Logo from "./_opengraph-image.png";

// export function generateMetadata() {
//   return {
//     openGraph: {
//       images: [Logo.src],
//     },
//   };
// }

export const metadata: Metadata = {
  title: "Hello",
  description: "Generated by create next app",
  metadataBase: new URL("https://thivy.github.io/github-pages-demo"),
  openGraph: {
    type: "website",
    url: "https://thivy.github.io/github-pages-demo",
    title: "Hello",
    description: "Generated by create next app",
    images: [Logo.src],
  },
};
